name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2


      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfdestroy

      - name: Terraform Destroy
        run: terraform apply -auto-approve tfdestroy

      - name: Clean up Terraform state artifacts
        run: rm -f terraform.tfstate terraform.tfstate.backup
